# --------------------------
# ðŸ”‘ MongoDB
MONGO_URI = "mongodb+srv://siddharthtomar003:oUIcyUk7xwraNjqp@cluster0.664o03z.mongodb.net/SIH"
DB_NAME = "SIH"
USERS_COLL = "users"
ISSUES_DB = "issue_tracker"
ISSUES_COLL = "issues"

# --------------------------
# ðŸ¤– Google Gemini API
GEMINI_API_KEY = "AIzaSyB-clc5NqNrV1ueQBj-nY4WOqwRRJOgIW8"

# --------------------------
# ðŸ“§ Gmail SMTP
MAIL_SERVER   = "smtp.gmail.com"
MAIL_PORT     = 465
MAIL_USERNAME = "mycardiocareindia@gmail.com"
MAIL_PASSWORD = "pevegxxdgsbawglh"   # <-- your Gmail App Password
MAIL_SENDER   = "mycardiocare@gmail.com"

# --------------------------
# ðŸ›¡ï¸ Flask/Streamlit secret key
SECRET_KEY = "your_secret_key"
